### ISSUE TITLE
Unnamed Tool Crash

### ISSUE THREAD

**Issue by Mustang351c** [SlimeKnights/IguanaTweaksTConstruct#185]
I recently had 3 tools change their name to unnamed and lose all data in the TiC tooltips. Upon placing them into a crafting grid, minecraft crashes. If any additional information is needed. I will be glad to give it to you. I should probably mention this happened after I messed with the config files generated after setting override module to true. I have since reverted that setting to false after I realized I had no idea what I was doing.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 10/1/15 10:13 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at iguanaman.iguanatweakstconstruct.OldToolConversionHandler.toolNeedsUpdating(OldToolConversionHandler.java:86)
	at iguanaman.iguanatweakstconstruct.ToolUpdateRecipe.func_77569_a(ToolUpdateRecipe.java:43)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at iguanaman.iguanatweakstconstruct.OldToolConversionHandler.toolNeedsUpdating(OldToolConversionHandler.java:86)
	at iguanaman.iguanatweakstconstruct.ToolUpdateRecipe.func_77569_a(ToolUpdateRecipe.java:43)
	at net.minecraft.item.crafting.CraftingManager.func_82787_a(CraftingManager.java:323)
	at net.minecraft.inventory.ContainerPlayer.func_75130_a(ContainerPlayer.java:80)
	at net.minecraft.inventory.InventoryCrafting.func_70299_a(SourceFile:81)
	at net.minecraft.inventory.Slot.func_75215_d(Slot.java:77)
	at net.minecraft.inventory.Container.func_75144_a(SourceFile:222)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78753_a(PlayerControllerMP.java:419)
	at codechicken.nei.guihook.GuiContainerManager.handleSlotClick(GuiContainerManager.java:504)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146984_a(GuiContainer.java:638)
	at net.minecraft.client.gui.inventory.GuiContainer.public_func_146984_a(GuiContainer.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.callHandleMouseClick(DefaultSlotClickHandler.java)
	at codechicken.nei.guihook.DefaultSlotClickHandler.handleSlotClick(DefaultSlotClickHandler.java:17)
	at codechicken.nei.guihook.GuiContainerManager.handleMouseClick(GuiContainerManager.java:453)
	at net.minecraft.client.gui.inventory.GuiContainer.managerHandleMouseClick(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146286_b(GuiContainer.java:607)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiInventory

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['mustang351c'/207, l='MpServer', x=-500.80, y=69.62, z=178.49]]
	Chunk stats: MultiplayerChunkCache: 121, 130
	Level seed: 0
	Level generator: ID 04 - ATG, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-224,64,256), Chunk: (at 0,4,0 in -14,16; contains blocks -224,0,256 to -209,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 3750883 game time, 4421143 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 62 total; [EntityItem['item.item.sulphur'/642, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityHuman['SethBling'/262, l='MpServer', x=-529.50, y=58.00, z=214.50], EntityCreeper['Creeper'/1809, l='MpServer', x=-519.31, y=51.00, z=190.98], EntityCreeper['Creeper'/1810, l='MpServer', x=-526.86, y=53.00, z=187.63], EntityCreeper['Creeper'/1811, l='MpServer', x=-526.50, y=53.00, z=181.50], EntityCreeper['Creeper'/1812, l='MpServer', x=-543.50, y=63.00, z=171.50], EntityCreeper['Creeper'/1686, l='MpServer', x=-3.20, y=-48.62, z=-16.49], EntitySpider['Spider'/1687, l='MpServer', x=-0.20, y=-49.62, z=-25.49], EntitySkeleton['Skeleton'/1688, l='MpServer', x=4.80, y=-47.62, z=-23.49], EntitySilverfish['Silverfish'/1689, l='MpServer', x=-14.92, y=-43.62, z=-23.79], EntityZombie['Zombie'/1690, l='MpServer', x=-14.19, y=-41.62, z=-23.46], EntityZombie['Zombie'/2210, l='MpServer', x=-501.50, y=39.00, z=199.50], EntitySkeleton['Skeleton'/2214, l='MpServer', x=-564.50, y=51.00, z=203.50], EntitySkeleton['Skeleton'/559, l='MpServer', x=-518.30, y=77.88, z=175.30], EntitySkeleton['Skeleton'/305, l='MpServer', x=-572.50, y=13.00, z=108.50], EntitySkeleton['Skeleton'/561, l='MpServer', x=-522.64, y=78.00, z=181.35], EntitySkeleton['Skeleton'/306, l='MpServer', x=-572.50, y=13.00, z=109.50], EntityZombie['Zombie'/307, l='MpServer', x=-571.50, y=13.00, z=109.50], EntitySnowman['Snow Golem'/186, l='MpServer', x=-503.50, y=69.00, z=180.50], EntityCreeper['Creeper'/187, l='MpServer', x=-541.22, y=20.00, z=140.84], EntityCreeper['Creeper'/188, l='MpServer', x=-514.59, y=50.00, z=173.94], EntityItem['item.item.1MinicioEssence'/191, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityItem['item.item.bone'/447, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityItem['item.item.arrow'/192, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityItem['item.item.rottenFlesh'/193, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityZombie['Zombie'/1733, l='MpServer', x=-523.50, y=54.00, z=204.50], EntityTameableDragon['Nether Dragon'/199, l='MpServer', x=-488.47, y=68.00, z=170.44], EntityXPOrb['Experience Orb'/201, l='MpServer', x=-531.63, y=58.75, z=142.88], EntityXPOrb['Experience Orb'/202, l='MpServer', x=-531.63, y=58.75, z=142.88], EntityXPOrb['Experience Orb'/203, l='MpServer', x=-531.63, y=58.75, z=142.88], EntitySkeleton['Skeleton'/204, l='MpServer', x=-560.50, y=41.00, z=170.50], EntityItem['item.item.string'/2252, l='MpServer', x=-518.13, y=78.00, z=175.13], EntityZombie['Zombie'/206, l='MpServer', x=-544.50, y=22.00, z=162.50], EntityCreeper['Creeper'/2766, l='MpServer', x=-567.50, y=51.00, z=200.50], EntityTrail['unknown'/847, l='MpServer', x=-500.80, y=69.62, z=178.49], EntitySpider['Spider'/208, l='MpServer', x=-579.25, y=76.00, z=101.06], EntityHuman['Imalune'/211, l='MpServer', x=-577.50, y=50.00, z=258.50], EntityBat['Bat'/212, l='MpServer', x=-560.78, y=23.00, z=219.75], EntityBat['Bat'/213, l='MpServer', x=-578.03, y=17.49, z=225.91], EntitySkeleton['Skeleton'/215, l='MpServer', x=-560.44, y=49.00, z=244.03], EntityBat['Bat'/220, l='MpServer', x=-549.34, y=47.10, z=242.50], EntitySkeleton['Skeleton'/2396, l='MpServer', x=-518.61, y=77.88, z=176.54], EntityHuman['W92Baj'/221, l='MpServer', x=-549.47, y=49.00, z=249.50], EntitySkeleton['Skeleton'/222, l='MpServer', x=-550.50, y=50.00, z=244.50], EntityHuman['skyzm'/223, l='MpServer', x=-546.50, y=50.00, z=246.50], EntitySquid['Squid'/225, l='MpServer', x=-530.59, y=58.06, z=239.28], EntityHuman['xbony2'/227, l='MpServer', x=-528.50, y=47.00, z=258.50], EntityClientPlayerMP['mustang351c'/207, l='MpServer', x=-500.80, y=69.62, z=178.49], EntityZombie['Zombie'/233, l='MpServer', x=-506.50, y=31.00, z=100.50], EntityCreeper['Creeper'/1769, l='MpServer', x=-504.50, y=61.00, z=202.50], EntityChicken['Omelette'/234, l='MpServer', x=-491.53, y=18.00, z=115.53], EntityZombie['Zombie'/235, l='MpServer', x=-491.50, y=25.00, z=134.50], EntityCreeper['Creeper'/236, l='MpServer', x=-468.50, y=58.00, z=106.50], EntitySkeleton['Skeleton'/237, l='MpServer', x=-456.69, y=61.27, z=109.70], EntityZombie['Zombie'/238, l='MpServer', x=-456.50, y=38.00, z=248.50], EntityBat['Bat'/241, l='MpServer', x=-447.75, y=59.10, z=167.75], EntityCreeper['Creeper'/242, l='MpServer', x=-441.41, y=52.00, z=190.06], EntityBat['Bat'/2162, l='MpServer', x=-525.25, y=59.00, z=214.75], EntityBat['Bat'/243, l='MpServer', x=-446.00, y=60.00, z=178.72], EntityCreeper['Creeper'/244, l='MpServer', x=-438.50, y=69.00, z=194.50], EntitySkeleton['Skeleton'/245, l='MpServer', x=-431.13, y=64.00, z=200.53], EntitySkeleton['Skeleton'/1532, l='MpServer', x=-488.50, y=23.00, z=208.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 469454848 bytes (447 MB) / 1662517248 bytes (1585 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 47527, allocated: 0, tallocated: 4096
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1492 Optifine OptiFine_1.7.10_HD_U_C1 77 mods loaded, 77 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1492} [Minecraft Forge] (forge-1.7.10-10.13.4.1492-1.7.10.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv2-stable-10} [AppliedEnergistics2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	OpenModsCore{0.8} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2{rv2-stable-10} [Applied Energistics 2] (appliedenergistics2-rv2-stable-10.jar) 
	UCHIJAAAA	ATG{0.10.0} [Alternate Terrain Generation] (ATG-1.7.10-0.12.0.jar) 
	UCHIJAAAA	BiblioCraft{1.11.2} [BiblioCraft] (BiblioCraft[v1.11.2][MC1.7.10].jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UCHIJAAAA	BnBTweaks{${version}} [Blood N' Bones Tweaks] (BnBTweaks-mc1.7.10-v1.0.1.jar) 
	UCHIJAAAA	CarpentersBlocks{3.3.7} [Carpenter's Blocks] (Carpenter's Blocks v3.3.7 - MC 1.7.10.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.0.3} [CoFH Core] (CoFHCore-[1.7.10]3.0.3-303.jar) 
	UCHIJAAAA	ComputerCraft{1.74} [ComputerCraft] (ComputerCraft1.74.jar) 
	UCHIJAAAA	defaultworldgenerator{0.1-b13} [Default World Generator] (DefaultWorldGenerator-1.7.10-0.1-b13-universal.jar) 
	UCHIJAAAA	DragonMounts{r41-1.7.10} [Dragon Mounts] (DragonMounts-r41-1.7.10.jar) 
	UCHIJAAAA	DynamicLights{1.3.8} [Dynamic Lights] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_onFire{1.0.4} [Dynamic Lights Burning Entity Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_creepers{1.0.4} [Dynamic Lights Creeper Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_dropItems{1.0.8} [Dynamic Lights EntityItem Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_entityClasses{1.0.1} [Dynamic Lights Entity Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_mobEquipment{1.0.8} [Dynamic Lights Mob Equipment Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_flameArrows{1.0.0} [Dynamic Lights Fiery Arrows Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_floodLights{1.0.2} [Dynamic Lights Flood Light] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_otherPlayers{1.0.8} [Dynamic Lights OtherPlayers Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	DynamicLights_thePlayer{1.1.4} [Dynamic Lights Player Light Module] (DynamicLights-1.7.10.jar) 
	UCHIJAAAA	eplus{3.0.2-d} [Enchanting Plus] (EnchantingPlus-1.7.10-3.0.2-d.jar) 
	UCHIJAAAA	endercore{1.7.10-0.1.0.24_beta} [EnderCore] (EnderCore-1.7.10-0.1.0.24_beta.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.415_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.415_beta.jar) 
	UCHIJAAAA	EnderStorage{1.4.7.33} [EnderStorage] (EnderStorage-1.7.10-1.4.7.33-universal.jar) 
	UCHIJAAAA	extracells{2.2.73} [Extra Cells 2] (ExtraCells-1.7.10-2.2.73b129.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins188} [Mantle] (Mantle-1.7.10-0.3.2a.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.7.build979} [Tinkers' Construct] (TConstruct-1.7.10-1.8.7.jar) 
	UCHIJAAAA	ExtraTiC{1.4.5} [ExtraTiC] (ExtraTiC-1.7.10-1.4.5.jar) 
	UCHIJAAAA	FastCraft{1.21} [FastCraft] (fastcraft-1.21.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAA	HardcoreDarkness{1.6} [Hardcore Darkness] (HardcoreDarkness-MC1.7.10-1.6.jar) 
	UCHIJAAAA	headcrumbs{1.6.0} [Headcrumbs] (Headcrumbs-1.6.0.jar) 
	UCHIJAAAA	iChunUtil{4.2.2} [iChunUtil] (iChunUtil-4.2.2.jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	JABBA{1.2.1} [JABBA] (Jabba-1.2.1a_1.7.10.jar) 
	UCHIJAAAA	magicalcrops{4.0.0_PUBLIC_BETA_4b} [Magical Crops: Core] (magicalcrops-4.0.0_PUBLIC_BETA_5.jar) 
	UCHIJAAAA	magicalcropsdeco{4.0.0_PUBLIC_BETA_4a} [Magical Crops: Decorative] (magicalcropsdeco-4.0.0_PUBLIC_BETA_4a.jar) 
	UCHIJAAAA	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.10.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	NetherOres{1.7.10R2.3.1RC1} [Nether Ores] (NetherOres-[1.7.10]2.3.1RC1-18.jar) 
	UCHIJAAAA	OpenMods{0.8} [OpenMods] (OpenModsLib-1.7.10-0.8.jar) 
	UCHIJAAAA	OpenBlocks{1.4.4} [OpenBlocks] (OpenBlocks-1.7.10-1.4.4.jar) 
	UCHIJAAAA	PortalGun{4.0.0-beta-5} [PortalGun] (PortalGun-4.0.0-beta-5.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.31} [MrTJPCore] (MrTJPCore-1.1.0.31-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre9.92} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre9.92-Base.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre9.92} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	ProjRed|Compatibility{4.7.0pre9.92} [ProjectRed Compatibility] (ProjectRed-1.7.10-4.7.0pre9.92-Compat.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre9.92} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre9.92-Integration.jar) 
	UCHIJAAAA	soundfilters{0.8_for_1.7.X} [Sound Filters] (SoundFilters-0.8_for_1.7.X.jar) 
	UCHIJAAAA	TiCTooltips{1.2.5} [TiC Tooltips] (TiCTooltips-mc1.7.10-1.2.5.jar) 
	UCHIJAAAA	TMechworks{0.2.14.100} [Tinkers' Mechworks] (TMechworks-1.7.10-0.2.14.100.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	VeinMiner{0.28.0_build.unknown} [Vein Miner] (VeinMiner-1.7.10_0.28.3.unknown.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.28.0_build.unknown} [Mod Support] (VeinMiner-1.7.10_0.28.3.unknown.jar) 
	UCHIJAAAA	wailaplugins{MC1.7.10-0.1.2-21} [WAILA Plugins] (WAILAPlugins-MC1.7.10-0.1.2-21.jar) 
	UCHIJAAAA	wawla{1.3.1} [What Are We Looking At] (Wawla-1.3.1-1.7.10.jar) 
	UCHIJAAAA	WR-CBE|Core{1.4.1.9} [WR-CBE Core] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Addons{1.4.1.9} [WR-CBE Addons] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	WR-CBE|Logic{1.4.1.9} [WR-CBE Logic] (WR-CBE-1.7.10-1.4.1.9-universal.jar) 
	UCHIJAAAA	zyinhud{1.3.9} [Zyin's HUD] (ZyinsHUD-(1.7.10)-v.1.3.9.jar) 
	UCHIJAAAA	bspkrsCore{6.16} [bspkrsCore] ([1.7.10]bspkrsCore-universal-6.16.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	IguanaTweaksTConstruct{1.7.10-2.1.5.140} [Iguana Tinker Tweaks] (IguanaTinkerTweaks-1.7.10-2.1.5.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4256' Renderer: 'Intel(R) HD Graphics 4400'
	OpenModsLib class transformers: [stencil_patches:FINISHED],[movement_callback:FINISHED],[map_gen_fix:FINISHED],[gl_capabilities_hook:FINISHED],[player_render_hook:FINISHED]
	Class transformer null safety: all safe
	AE2 Version: stable rv2-stable-10 for Forge 10.13.2.1291
	CoFHCore: -[1.7.10]3.0.3-303
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
	TConstruct Environment: Environment healthy.
	NetherOres: -[1.7.10]2.3.1RC1-18
	EnderIO: Found the following problem(s) with your installation: "Optifine is installed. This is NOT supported." This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	Stencil buffer state: Function set: GL30, pool: forge, bits: 8
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BC:OFF, RF:ON, RFItem:ON, MFR:OFF, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, InvTweaks:ON, NEI:ON, CraftGuide:OFF, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF
	Launched Version: forge-10.13.4.1492
	LWJGL: 2.9.1
	OpenGL: Intel(R) HD Graphics 4400 GL version 4.3.0 - Build 10.18.15.4256, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by Mustang351c** [comment]
never mind. I accidentally deleted Metallurgy.
