### ISSUE TITLE
1.7.10-2.1.2.109 - Crash world down

### ISSUE THREAD

**Issue by mezoty** [SlimeKnights/IguanaTweaksTConstruct#85]
Description: Exception getting block type in world

java.lang.NoSuchFieldError: modAttack
at iguanaman.iguanatweakstconstruct.leveling.RandomBonuses.<clinit>(RandomBonuses.java:75)
at iguanaman.iguanatweakstconstruct.worldgen.RandomWeaponChestContent.generateChestContent(RandomWeaponChestContent.java:107)
	at net.minecraft.util.WeightedRandomChestContent.func_76293_a(WeightedRandomChestContent.java:38)
	at net.minecraft.world.gen.feature.WorldGenDungeons.func_76484_a(WorldGenDungeons.java:133)
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:418)
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:279)
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1050)
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:190)
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:131)
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:101)
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:199)
	at net.minecraft.world.World.func_72964_e(World.java:419)
	at net.minecraft.world.World.func_147439_a(World.java:345)
	at net.minecraft.world.World.func_147437_c(World.java:365)
	at net.minecraft.block.BlockStaticLiquid.func_149674_a(SourceFile:55)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:391)
	at WorldServerOF.func_147456_g(WorldServerOF.java:477)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:183)
	at WorldServerOF.func_72835_b(WorldServerOF.java:234)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:625)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by bonii-xx** [comment]
You're using incompatible versions.
